export enum UserTypes {
  ADMIN = 'ADMIN',
  CUSTOMER = 'CUSTOMER',
  OUTLET_AGENT = 'OUTLET_AGENT',
  CENTRAL_STAFF = 'CENTRAL_STAFF',
  PURCHASE_STAFF = 'PURCHASE_STAFF',
  SUPPLIER = 'SUPPLIER',
}

export enum ProductUnits {
  KG = 'KG',
  G = 'G',
}

export enum OrderStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  DISPATCHED = 'DISPATCHED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentMethod {
  COD = 'COD',
  UPI = 'UPI',
}

export enum PaymentStatus {
  NOT_REQUIRED = 'NOT_REQUIRED',
  AWAITING_SCREENSHOT = 'AWAITING_SCREENSHOT',
  AWAITING_VERIFICATION = 'AWAITING_VERIFICATION',
  VERIFIED = 'VERIFIED',
}
