import { DataSource } from 'typeorm';
import { Ward } from './entities/ward.entity';

const wards = [
  { wardNumber: '1', name: 'FORT KOCHI' },
  { wardNumber: '2', name: 'KALVATHY' },
  { wardNumber: '3', name: 'EARAVELY' },
  { wardNumber: '4', name: 'KARIPPALAM' },
  { wardNumber: '5', name: 'CHERALAYI' },
  { wardNumber: '6', name: 'MATTANCHERY' },
  { wardNumber: '7', name: 'CHAKKAMADAM' },
  { wardNumber: '8', name: 'KARUVELIPPADY' },
  { wardNumber: '9', name: 'ISLAND NORTH' },
  { wardNumber: '10', name: 'RAVIPURAM' },
  { wardNumber: '11', name: 'ERNAKULAM SOUTH' },
  { wardNumber: '12', name: 'GANDHI NAGAR' },
  { wardNumber: '13', name: 'KATHRIKADAVU' },
  { wardNumber: '14', name: 'ERNAKULAM CENTRAL' },
  { wardNumber: '15', name: 'ERNAKULAM NORTH' },
  { wardNumber: '16', name: 'KALOOR SOUTH' },
  { wardNumber: '17', name: 'KALOOR-NORTH' },
  { wardNumber: '18', name: 'THRIKKANARVATTOM' },
  { wardNumber: '19', name: 'AYYAPPANKAVU' },
  { wardNumber: '20', name: 'POTTAKUZHY' },
  { wardNumber: '21', name: 'ELAMAKKARA SOUTH' },
  { wardNumber: '22', name: 'PACHALAM' },
  { wardNumber: '23', name: 'THATTAZHAM' },
  { wardNumber: '24', name: 'VADUTHALA WEST' },
  { wardNumber: '25', name: 'VADUTHALA EAST' },
  { wardNumber: '26', name: 'ELAMAKKARA NORTH' },
  { wardNumber: '27', name: 'PUTHUKKALAVATTAM' },
  { wardNumber: '28', name: 'KUNNUMPURAM' },
  { wardNumber: '29', name: 'PONEKKARA' },
  { wardNumber: '30', name: 'EDAPPALLY' },
  { wardNumber: '31', name: 'CHANGAMPUZHA' },
  { wardNumber: '32', name: 'DHEVANKULANGARA' },
  { wardNumber: '33', name: 'PALARIVATTAM' },
  { wardNumber: '34', name: 'STADIUM' },
  { wardNumber: '35', name: 'KARANAKKODAM' },
  { wardNumber: '36', name: 'PUTHIYAROAD' },
  { wardNumber: '37', name: 'PADIVATTAM' },
  { wardNumber: '38', name: 'VENNALA' },
  { wardNumber: '39', name: 'CHAKKARAPARAMBU' },
  { wardNumber: '40', name: 'CHALIKKAVATTAM' },
  { wardNumber: '41', name: 'THAMMANAM' },
  { wardNumber: '42', name: 'ELAMKULAM' },
  { wardNumber: '43', name: 'GIRINAGAR' },
  { wardNumber: '44', name: 'PONNURUNNI' },
  { wardNumber: '45', name: 'PONNURUNNI EAST' },
  { wardNumber: '46', name: 'VYTTILA' },
  { wardNumber: '47', name: 'POONITHURA' },
  { wardNumber: '48', name: 'VYTTILA JANATHA' },
  { wardNumber: '49', name: 'KADAVANTHRA' },
  { wardNumber: '50', name: 'PANAMPILLI NAGAR' },
  { wardNumber: '51', name: 'PERUMANOOR' },
  { wardNumber: '52', name: 'KONTHURUTHY' },
  { wardNumber: '53', name: 'THEVARA' },
  { wardNumber: '54', name: 'ISLAND SOUTH' },
  { wardNumber: '55', name: 'KADEBHAGAM' },
  { wardNumber: '56', name: 'PALLURUTHY EAST' },
  { wardNumber: '57', name: 'THAZHUPPU' },
  { wardNumber: '58', name: 'EADAKOCHI NORTH' },
  { wardNumber: '59', name: 'EDAKOCHI SOUTH' },
  { wardNumber: '60', name: 'PERUMBADAPPU' },
  { wardNumber: '61', name: 'KONAM' },
  { wardNumber: '62', name: 'PALLURUTHY-KACHERIPADY' },
  { wardNumber: '63', name: 'NAMBYAPURAM' },
  { wardNumber: '64', name: 'PALLURUTHY' },
  { wardNumber: '65', name: 'PULLARDESAM' },
  { wardNumber: '66', name: 'THAREBHAGAM' },
  { wardNumber: '67', name: 'THOPPUMPADY' },
  { wardNumber: '68', name: 'MUNDAMVELY EAST' },
  { wardNumber: '69', name: 'MUNDAMVELY' },
  { wardNumber: '70', name: 'MANASSERY' },
  { wardNumber: '71', name: 'MOOLAMKUZHY' },
  { wardNumber: '72', name: 'CHULLICKAL' },
  { wardNumber: '73', name: 'NASRATHU' },
  { wardNumber: '74', name: 'PANAYAPPILLY' },
  { wardNumber: '75', name: 'AMARAVATHY' },
  { wardNumber: '76', name: 'FORTKOCHI VELI' },
];

export async function seedWards(dataSource: DataSource) {
  const repo = dataSource.getRepository(Ward);
  const existing = await repo.count();
  if (existing > 0) {
    console.log(`Wards already seeded (${existing} records). Skipping.`);
    return;
  }
  await repo.save(wards.map((w) => repo.create(w)));
  console.log(`Seeded ${wards.length} wards.`);
}
